name: jupyterlab-pytutor-lite

channels:
- conda-forge

dependencies:
- build
- python=3.10
- mamba
- pydata-sphinx-theme
- myst-parser
- ipywidgets>=8.0,<9
- jupyterlab>=4.0.0,<5
- jupyterlab-language-pack-fr-FR
- jupyterlab-language-pack-zh-CN
- nodejs=18
- pip:
  - jupyterlite-sphinx
  - jupyterlite==0.1.0b17
